name: clean_architecture_todo_app
description: CleanArchitecuture ToDo App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dain: ^0.1.2
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^1.0.0-dev.5
  rxdart: ^0.27.1
  sqflite: ^2.0.0+3
  state_notifier: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.2
  mockito: ^5.0.10

flutter:
  uses-material-design: true
